name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libgtest-dev

    - name: Set up CMake
      uses: lukka/get-cmake@v3.30.5
      with:
        cmakeVersion: 3.29

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    # provide the binary as an artifact
    - name: Run tests
      run: ctest -C Debug -VV