on:
  workflow_dispatch:
  push:

jobs:
  build:
    # compile the Cmake project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.29'

      - name: Build
        run: cmake -B build && cmake --build build